<div class="float">
	<br />
	<h2>ABOUT</h2>
  <!--<p><h3>Purpose</h3>
    Computers are complicated and many repair companies take advantage of that by convincing you that you need certain products or services. Even the companies that make computer operating systems often build their products in a way that force you to buy more of their products to stay relevant. I want that to change though, and this is my way of helping that happen. I use methods that elimnate the need for antivirus programs and repeated expensive repairs. I install operating systems and programs that are free to anyone and therefore not compromised by the agenda of its creator. I believe that our country would benefit from the low cost, security, and collaboration of the open source movement.</p>-->
  <p><h3>How do we do it?</h3>
    We use an operating system called Linux which is also used by companies like <b>Google</b>, <b>Amazon</b>, and <b>GoDaddy</b>. It is even what <b>Android</b> cellphones are built on. Linux is community made which means there are no copyrights or patents. So anyone is free to improve on it. Because it is always being updated, it is almost impossible to get viruses on it. Not to mention it is fully customizable. If there are things you don't like about your new setup, you can change it however you want.</p>
  <p><h3>What is Open Source?</h3>
    <!--<img src='images/tuxpc.png' width='400' align='right' />-->
    <center><iframe width="640" height="360" src="//www.youtube.com/embed/a8fHgx9mE5U?rel=0" frameborder="0" allowfullscreen></iframe></center>
    <!--Open source is a term that refers to software whose source code is freely available. Anyone can copy the source code and make their own version or fix problems in the program. An easy way to explain is by thinking of a really good home cooked meal. You sit down and eat at a friend's house and you really like the main dish. But you can only really guess as to how it was made unless you have their recipe. Once you have that recipe, you can alter certain ingredients or even use that recipe as a base for a more complex meal. Open source works the same way. Instead of locking down a recipe and keeping for yourself, it is made freely available and therefore anyone who knows how can improve on it. It also proves to be more secure. You can check if the program lets people spy on you because you can view the source code. Where as other companies build in backdoors for the government or themselves to track you and there is no way to see because their source (or recipe) is hidden.--></p>
	<p><h3>Why Linux?</h3>
	Some people think Linux is a very difficult operating system to use. It used to be, but it has come a long way. Many versions of Linux are extremely user-friendly and many people find that they like it better than other operating systems. Not to mention, the copyrights and patents on other operating systems out there limit invention. With Linux, people can build on the progress of others. Linux is known for its security, lack of viruses, and its speed and I believe that it deserves more attention as an every day operating system.</p>
</div>
